signomix.image.group.default=
quarks.container-image.builder=jib
quarkus.jib.base-jvm-image=registry.access.redhat.com/ubi9/openjdk-21-runtime:1.21
quarkus.container-image.group=${SIGNOMIX_IMAGE_GROUP:${signomix.image.group.default}}
quarkus.container-image.name=${SIGNOMIX_IMAGE_NAME:signomix-sentinel}
quarkus.container-image.tag=${SIGNOMIX_IMAGE_TAG:%release%}

# Instruct SmallRye to read properties from files in /run/secrets
smallrye.config.source.file.locations=/run/secrets

signomix.signals.used=${SIGNOMIX_SIGNALS_USED:false}

## HTTP
quarkus.http.port=${PORT:8080}
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.access-log.enabled=true

## LOGGING
quarkus.log.level=${SIGNOMIX_LOG_LEVEL:INFO}

# Syslog handler configuration
quarkus.log.syslog.enabled=true
quarkus.log.syslog.app-name=signomix-sentinel
quarkus.log.syslog.hostname=local-dev
quarkus.log.syslog.endpoint=phoenix3:5140
quarkus.log.syslog.protocol=TCP
quarkus.log.syslog.level=ALL
#quarkus.log.syslog.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] (%t) %s%e%n

## DATASOURCES
signomix.database.type=${SIGNOMIX_DATABASE_TYPE:postgresql}
quarkus.datasource.oltp.db-kind=postgresql
quarkus.datasource.oltp.username=${postgres_user}
quarkus.datasource.oltp.password=${postgres_password}
quarkus.datasource.oltp.jdbc.url=${postgres_url}
#quarkus.datasource.oltp.jdbc.telemetry=true


quarkus.datasource.olap.db-kind=postgresql
quarkus.datasource.olap.username=${postgres_user}
quarkus.datasource.olap.password=${postgres_password}
quarkus.datasource.olap.jdbc.url=${postgres_url}
#quarkus.datasource.olap.jdbc.telemetry=true

quarkus.datasource.auth.db-kind=postgresql
quarkus.datasource.auth.username=${postgres_user}
quarkus.datasource.auth.password=${postgres_password}
quarkus.datasource.auth.jdbc.url=${postgres_url}
#quarkus.datasource.auth.jdbc.telemetry=true

quarkus.datasource.user.db-kind=postgresql
quarkus.datasource.user.username=${postgres_user}
quarkus.datasource.user.password=${postgres_password}
quarkus.datasource.user.jdbc.url=${postgres_url}
#quarkus.datasource.user.jdbc.telemetry=true

questdb.client.config=${questdb_config}

## MQTT
mp.messaging.connector.smallrye-mqtt.auto-clean-session=false

mp.messaging.incoming.command-created.connector=smallrye-mqtt
mp.messaging.incoming.command-created.qos=1
mp.messaging.incoming.command-created.host=signomix-broker
mp.messaging.incoming.command-created.port=1883
mp.messaging.incoming.command-created.topic=signomix/events/command-created
mp.messaging.incoming.command-created.client-id=signomix-sentinel

mp.messaging.incoming.data-received.connector=smallrye-mqtt
mp.messaging.incoming.data-received.qos=1
mp.messaging.incoming.data-received.host=signomix-broker
mp.messaging.incoming.data-received.port=1883
mp.messaging.incoming.data-received.topic=signomix/events/data-received
mp.messaging.incoming.data-received.client-id=signomix-sentinel

mp.messaging.incoming.device-created.connector=smallrye-mqtt
mp.messaging.incoming.device-created.qos=1
mp.messaging.incoming.device-created.host=signomix-broker
mp.messaging.incoming.device-created.port=1883
mp.messaging.incoming.device-created.topic=signomix/events/device-created
mp.messaging.incoming.device-created.client-id=signomix-sentinel

mp.messaging.incoming.device-removed.connector=smallrye-mqtt
mp.messaging.incoming.device-removed.qos=1
mp.messaging.incoming.device-removed.host=signomix-broker
mp.messaging.incoming.device-removed.port=1883
mp.messaging.incoming.device-removed.topic=signomix/events/device-removed
mp.messaging.incoming.device-removed.client-id=signomix-sentinel

mp.messaging.incoming.device-updated.connector=smallrye-mqtt
mp.messaging.incoming.device-updated.qos=1
mp.messaging.incoming.device-updated.host=signomix-broker
mp.messaging.incoming.device-updated.port=1883
mp.messaging.incoming.device-updated.topic=signomix/events/device-updated
mp.messaging.incoming.device-updated.client-id=signomix-sentinel

mp.messaging.outgoing.alerts.connector=smallrye-mqtt
mp.messaging.outgoing.alerts.qos=1
mp.messaging.outgoing.alerts.host=signomix-broker
mp.messaging.outgoing.alerts.port=1883
mp.messaging.outgoing.alerts.topic=signomix/alerts
mp.messaging.outgoing.alerts.client-id=signomix-sentinel
mp.messaging.outgoing.alerts.merge=true

## OPENAPI
quarkus.smallrye-openapi.path=/api/sentinel
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/api/sentinel/q/swagger

## OPEN TELEMTRY
quarkus.otel.service.name=${SIGNOMIX_SENTINEL_OTEL_NAME:signomix-sentinel}
quarkus.otel.exporter.otlp.endpoint=${otel_service_url}
quarkus.otel.exporter.otlp.headers=${otel_service_headers}
quarkus.otel.logs.enabled=true
quarkus.otel.logs.level=INFO
